### ISSUE TITLE
Urgent: Documentation Needs Fixing

### ISSUE THREAD

**Issue by mrhillsman** [Infinidat/infinibox-csi-driver#106]
Hi, I work on the Red Hat Operator Enablement team and upon review of the Infinibox operator we found the documentation to be severely lacking required information for successful use of the operator; please see attached screenshots

![04](https://user-images.githubusercontent.com/3989695/89546749-8bf9f000-d7ca-11ea-828f-70b0e66de624.png)
![05](https://user-images.githubusercontent.com/3989695/89546753-8c928680-d7ca-11ea-8a24-b44ac6b9d0ed.png)

Here is an example of an Operator providing some good documentation as a reference. I am only pointing out examples of their usage of their operator's "logo", headings, ordered lists, hyperlinks, etc.

![01](https://user-images.githubusercontent.com/3989695/89546739-8a302c80-d7ca-11ea-865e-d21b58adbf62.png)
![02](https://user-images.githubusercontent.com/3989695/89546741-8ac8c300-d7ca-11ea-9e8a-db3553f88c95.png)
![03](https://user-images.githubusercontent.com/3989695/89546748-8bf9f000-d7ca-11ea-9040-5f7253ee19eb.png)

Also there is a bug open for this and if required we can provide reasonable assistance where necessary to get this resolved: https://bugzilla.redhat.com/show_bug.cgi?id=1856040

**Comment by ekaulberg** [comment]
Hi @mrhillsman, thanks for providing the feedback. We will sync internally to get an action plan for appropriate updates.

**Comment by mrhillsman** [comment]
Thanks for the update @ekaulberg appreciate the quick response.

**Comment by ekaulberg** [comment]
We included big improvements to our Operator metadata docs in our CSI release 2.1.0, see OperatorHub listing and please advise if there is anything else outstanding.
