### ISSUE TITLE
Kubernetes 1.25 support

### ISSUE THREAD

**Issue by jpuskar** [Infinidat/infinibox-csi-driver#110]
Greetings,
Any idea when this CSI will support 1.24 or 1.25?

K8s 1.23 will be EoL soon.

Thanks!

**Comment by ozzzik** [comment]
@jpuskar Hi, we will add support for 1.25 on our next release (2.2.0)

**Comment by sqqqrly** [comment]
I am pleased to announce that CSI Driver v2.3.1 is now GA.

What’s new in this release:
NFS-TreeQ is now supported for Kubernetes 1.23-1.25 and for RedHat OpenShift 4.8-4.11
NFS-TreeQ limitations are now optional within the StorageClass file
