### ISSUE TITLE
Harden 7 security vulnerabilities

### ISSUE THREAD

**Issue by singlecheeze** [Infinidat/infinibox-csi-driver#117]
https://catalog.redhat.com/software/containers/infinidat/infinibox-csidriver-certified/5ea20d9c2937381642a22cf6?container-tabs=security

![image](https://github.com/user-attachments/assets/1cd31ab0-44b1-44ae-9df3-81c4aeb21596)

Please consider hardening the CSI as per Red Hat tracked CVE/RHSA

Please note, last CSI release was 3 days before many patches were made to certain UBIs

**Comment by jmccormick2001** [comment]
should be fixed with the upcoming 4.17 release as it will be based on the latest ubi base image which should fix those issues.
