### ISSUE TITLE
Host LUN Masking for Existing Host Entry

### ISSUE THREAD

**Issue by singlecheeze** [Infinidat/infinibox-csi-driver#119]
There may be an issue with a host entry creation via CSI vs a host entry that might already be present on the Infinibox:
![image](https://github.com/user-attachments/assets/1eb5e3ac-b63a-446e-9e5e-ee76bf37bb98)

See 59 LUNs mapped to a host entry that has zero ports mapped.

Does the CSI consistently us host FQDN or short name when it tries to see if a host entry already exists; and if not create a new host entry?

Additionally, it appears like the host entry check is a fuzzy search, therefore a DNS short name would pass the substring check of `strings.Contains` here: https://github.com/Infinidat/infinibox-csi-driver/blob/bcbb622290a5aa393e948568e9f14d90f3e6aeda/storage/fcnode.go#L94

**Comment by jmccormick2001** [comment]
I've dug into this some, that comparison I think is ok, it does port name comparisions essentially...

fcnode.go:96 NodeStageVolume comparing  with 21000024ff84caa0
^[[90m2024-10-18T15:52:45.874595693Z^[[0m | DEBUG | fcnode.go:98 host port 21000024ff84caa0 is not created, creating it

however, the node name that gets created on the ibox is essentially from a 'hostname -f' command.  Typically this will return the fully qualified name.  I'm not sure under what case it would show a domain name and in other cases not show a domain name.

**Comment by singlecheeze** [comment]
I've done some research on this too, I wonder if the nodes are getting a DNS shortname from DHCP as `hostname -f` should be the FQDN:
```text
sh-5.1# hostname -f
r730ocp5.localdomain
sh-5.1# hostnamectl status --static
r730ocp5.localdomain
sh-5.1# hostnamectl status         
 Static hostname: r730ocp5.localdomain
       Icon name: computer-server
         Chassis: server 🖳
      Machine ID: ab99d94692b944f4b4bdc6405a63e664
         Boot ID: 5aadcc3c5c6b405bb089a18da5dde80e
Operating System: Red Hat Enterprise Linux CoreOS 417.94.202409121747-0
     CPE OS Name: cpe:/o:redhat:enterprise_linux:9::baseos::coreos
          Kernel: Linux 5.14.0-427.35.1.el9_4.x86_64
    Architecture: x86-64
 Hardware Vendor: Dell Inc.
  Hardware Model: PowerEdge R730xd
Firmware Version: 2.19.0
```
```
~$ hostname -h
Usage: hostname [-b] {hostname|-F file}         set host name (from file)
       hostname [-a|-A|-d|-f|-i|-I|-s|-y]       display formatted name
       hostname                                 display host name

       {yp,nis,}domainname {nisdomain|-F file}  set NIS domain name (from file)
       {yp,nis,}domainname                      display NIS domain name

       dnsdomainname                            display dns domain name

       hostname -V|--version|-h|--help          print info and exit

Program name:
       {yp,nis,}domainname=hostname -y
       dnsdomainname=hostname -d

Program options:
    -a, --alias            alias names
    -A, --all-fqdns        all long host names (FQDNs)
    -b, --boot             set default hostname if none available
    -d, --domain           DNS domain name
    -f, --fqdn, --long     long host name (FQDN)
    -F, --file             read host name or NIS domain name from given file
    -i, --ip-address       addresses for the host name
    -I, --all-ip-addresses all addresses for the host
    -s, --short            short host name
    -y, --yp, --nis        NIS/YP domain name

Description:
   This command can get or set the host name or the NIS domain name. You can
   also get the DNS domain or the FQDN (fully qualified domain name).
   Unless you are using bind or NIS for host lookups you can change the
   FQDN (Fully Qualified Domain Name) and the DNS domain name (which is
   part of the FQDN) in the /etc/hosts file.
```

**Comment by jmccormick2001** [comment]
side note, in cases where a user doesn't want to or can't use a host name that has a domain name that is too long, we created a feature a few releases ago that will cause the domain name to be chopped off, resulting in only using the short name.  That feature is the 'removeDomainName' setting in the CR.  If set to true, then the short name will always be used.   Not sure if that was mistakenly used at one point when installing the CSI driver or not.

**Comment by singlecheeze** [comment]
@jmccormick2001 thank you for bringing that to our attention, I'll make sure we standardize on `removeDomainName` set to true as that will resolve any questions we might have around DHCP reservations potentially not matching DNS or anything in that regard... 

Further, given that I think there is an obscure setting somewhere that DNS search domains must be limited to 211 characters or something like that in k8s, I would encourage the team to pre-emptively just set this setting to true out-of-the-box.

If I find the github link I'll post it...

**Comment by jmccormick2001** [comment]
not much here that needs to be done, going to close for now.
